/**
 * Bridge — Initialise the .factory folder in a target repo.
 *
 * The .factory folder is the structured contract between a repo and
 * the factory.  It contains:
 *   factory.yaml  — manifest (what the repo exposes)
 *   specs/apps/   — app spec YAMLs
 *   specs/features/ — feature spec YAMLs
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { stringify as toYaml, parse as parseYaml } from 'yaml';
import { ensureDir, writeFile, log } from './utils.ts';

// ─── Types ────────────────────────────────────────────────

export interface BridgeConfig {
    version: number;
    name: string;
    description: string;
    registry?: { apps?: string };
    conventions?: { rules?: string; agents?: string };
    skills?: Array<{ app: string; path: string }>;
    templates?: { starter?: string };
    apps_dir?: string;
}

// Files to look for when auto-discovering skills
const SKILL_FILENAMES = ['skills.md', 'SKILL.md', 'agents.md', 'AGENTS.md'];

// ─── Public API ───────────────────────────────────────────

/**
 * Initialise or refresh the .factory bridge in a target repo.
 * If factory.yaml already exists, it is preserved.  Otherwise one
 * is generated by scanning the repo.
 */
export function initBridge(repoPath: string): BridgeConfig {
    if (!existsSync(repoPath)) {
        throw new Error(`Repo not found: ${repoPath}`);
    }

    const factoryDir = join(repoPath, '.factory');
    const manifestPath = join(factoryDir, 'factory.yaml');

    // If manifest already exists, load and return it
    if (existsSync(manifestPath)) {
        log('●', '.factory/factory.yaml already exists — preserving');
        const config = loadBridgeConfig(repoPath);
        ensureDirectories(factoryDir);
        return config;
    }

    // Auto-discover and generate
    log('●', 'Scanning repo and creating .factory bridge...');
    const config = discoverBridgeConfig(repoPath);

    // Create structure
    ensureDir(factoryDir);
    ensureDirectories(factoryDir);

    // Write manifest
    writeFile(manifestPath, toYaml(config) + '\n');

    log('✓', `Bridge created at ${factoryDir}`);
    log('  ', `  Name: ${config.name}`);
    log('  ', `  Apps dir: ${config.apps_dir || 'apps'}`);
    log('  ', `  Skills: ${config.skills?.length || 0} files discovered`);

    return config;
}

/**
 * Load an existing factory.yaml from a repo.
 */
export function loadBridgeConfig(repoPath: string): BridgeConfig {
    const manifestPath = join(repoPath, '.factory', 'factory.yaml');
    if (!existsSync(manifestPath)) {
        throw new Error(`No .factory/factory.yaml found in ${repoPath}`);
    }
    return parseYaml(readFileSync(manifestPath, 'utf-8')) as BridgeConfig;
}

/**
 * Check whether a repo already has a .factory bridge.
 */
export function hasBridge(repoPath: string): boolean {
    return existsSync(join(repoPath, '.factory', 'factory.yaml'));
}

// ─── Internal ─────────────────────────────────────────────

function ensureDirectories(factoryDir: string): void {
    ensureDir(join(factoryDir, 'specs', 'apps'));
    ensureDir(join(factoryDir, 'specs', 'features'));
}

/**
 * Scan a repo and build a BridgeConfig by auto-discovering known files.
 */
function discoverBridgeConfig(repoPath: string): BridgeConfig {
    const config: BridgeConfig = {
        version: 1,
        name: guessRepoName(repoPath),
        description: '',
    };

    // 1. Registry — look for apps.json
    if (existsSync(join(repoPath, 'apps.json'))) {
        config.registry = { apps: 'apps.json' };
        log('  ', '  ✓ Found apps.json');
    }

    // 2. Conventions — look for .agent/rules/ and AGENTS.md
    const rulesDir = join(repoPath, '.agent', 'rules');
    const agentsFile = join(repoPath, 'AGENTS.md');
    if (existsSync(rulesDir) || existsSync(agentsFile)) {
        config.conventions = {};
        if (existsSync(rulesDir)) {
            config.conventions.rules = '.agent/rules';
            log('  ', '  ✓ Found .agent/rules/');
        }
        if (existsSync(agentsFile)) {
            config.conventions.agents = 'AGENTS.md';
            log('  ', '  ✓ Found AGENTS.md');
        }
    }

    // 3. Skills — scan apps/ for skill/agent files
    const appsDir = join(repoPath, 'apps');
    if (existsSync(appsDir)) {
        config.apps_dir = 'apps';
        const skills: Array<{ app: string; path: string }> = [];
        const appDirs = readdirSync(appsDir, { withFileTypes: true })
            .filter(d => d.isDirectory())
            .map(d => d.name);

        for (const appName of appDirs) {
            for (const filename of SKILL_FILENAMES) {
                const skillPath = join(appsDir, appName, filename);
                if (existsSync(skillPath)) {
                    const relPath = relative(repoPath, skillPath);
                    skills.push({ app: appName, path: relPath });
                    log('  ', `  ✓ Found ${relPath}`);
                }
            }
        }

        if (skills.length > 0) {
            config.skills = skills;
        }
    }

    // 4. Templates — look for apps/starter
    if (existsSync(join(repoPath, 'apps', 'starter'))) {
        config.templates = { starter: 'apps/starter' };
        log('  ', '  ✓ Found apps/starter template');
    }

    return config;
}

function guessRepoName(repoPath: string): string {
    // Try package.json
    const pkgPath = join(repoPath, 'package.json');
    if (existsSync(pkgPath)) {
        try {
            const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'));
            if (pkg.name) return pkg.name;
        } catch { /* ignore */ }
    }
    // Fall back to directory name
    return repoPath.split('/').pop() || 'unknown';
}
