/**
 * Report generator — produces a build report after scaffolding.
 */

import { resolve } from 'node:path';
import type { AppSpec, BuildReport, ValidationResult } from './types.ts';
import { PATHS, writeFile, timestamp, log } from './utils.ts';
import { listFiles } from './scaffold.ts';

/**
 * Generate a build report for a scaffolded app.
 *
 * @param spec - The parsed app spec
 * @param validation - Validation results
 * @returns The generated BuildReport
 */
export function generateReport(spec: AppSpec, validation: ValidationResult): BuildReport {
    const outputDir = resolve(PATHS.output, spec.metadata.slug);
    const patchDir = resolve(outputDir, 'patches');

    const filesGenerated = listFiles(outputDir).filter(f => !f.startsWith('patches/'));
    const patchesGenerated = listFiles(patchDir);

    const report: BuildReport = {
        spec: spec.metadata.slug,
        slug: spec.metadata.slug,
        timestamp: timestamp(),
        filesGenerated,
        patchesGenerated,
        validation,
        nextSteps: [
            `Copy output/${spec.metadata.slug}/ into monorepo at apps/${spec.metadata.slug}/`,
            'Apply patches from patches/ directory (see patches/APPLY.md)',
            'Run pnpm install in monorepo root',
            `Run pnpm build --filter @saveaday/${spec.metadata.slug}`,
            'Create .env.local from .env.example',
            `Start with pnpm dev --filter @saveaday/${spec.metadata.slug}`,
        ],
    };

    // Write markdown report
    const md = formatReport(report, spec);
    const reportPath = resolve(PATHS.reports, `${spec.metadata.slug}-${Date.now()}.md`);
    writeFile(reportPath, md);

    log('✓', `Report written to ${reportPath}`);

    return report;
}

/**
 * Format a build report as Markdown.
 */
function formatReport(report: BuildReport, spec: AppSpec): string {
    const validationLines = report.validation.checks
        .map(c => `| ${c.passed ? '✅' : '❌'} | ${c.name} | ${c.message} |`)
        .join('\n');

    return `# Build Report: ${spec.metadata.name}

**Slug**: \`${report.slug}\`
**Generated**: ${report.timestamp}
**Status**: ${report.validation.passed ? '✅ All checks passed' : '❌ Some checks failed'}

---

## App Summary

| Property | Value |
|---|---|
| Name | ${spec.metadata.name} |
| Slug | ${spec.metadata.slug} |
| Icon | ${spec.metadata.icon} |
| Port | ${spec.deployment.port} |
| Region | ${spec.deployment.region} |
| Database ID | ${spec.database.firestoreId} |
| Collections | ${spec.database.collections.join(', ')} |
| Resources | ${spec.api.resources.map(r => r.name).join(', ')} |

---

## Validation Results

| Status | Check | Details |
|---|---|---|
${validationLines}

---

## Files Generated (${report.filesGenerated.length})

\`\`\`
${report.filesGenerated.join('\n')}
\`\`\`

## Patches Generated (${report.patchesGenerated.length})

\`\`\`
${report.patchesGenerated.join('\n')}
\`\`\`

---

## Next Steps

${report.nextSteps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

---

*Generated by saveaday-factory*
`;
}
