// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYyZ-c-nP44Qw4iQ2IvT3_13nLmgqiVGU',
    appId: '1:69536493117:android:e9e2ad1f92324302918454',
    messagingSenderId: '69536493117',
    projectId: 'fikr-apps',
    storageBucket: 'fikr-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnAddSxl7V3T6X3jeh6AGvf4zYGm_VJnU',
    appId: '1:69536493117:ios:1a966886459895b8918454',
    messagingSenderId: '69536493117',
    projectId: 'fikr-apps',
    storageBucket: 'fikr-apps.firebasestorage.app',
    iosClientId: '69536493117-ikuuen4q38fq8f8rb4mn5ngeqk0birp4.apps.googleusercontent.com',
    iosBundleId: 'com.bigmints.fikr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnAddSxl7V3T6X3jeh6AGvf4zYGm_VJnU',
    appId: '1:69536493117:ios:7606a7260da1c636918454',
    messagingSenderId: '69536493117',
    projectId: 'fikr-apps',
    storageBucket: 'fikr-apps.firebasestorage.app',
    iosBundleId: 'com.fikr.fikr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5--E7OtwFbMRV8PFOlwnMHP6BAMFBWpA',
    appId: '1:69536493117:web:4324ecabc81d6591918454',
    messagingSenderId: '69536493117',
    projectId: 'fikr-apps',
    authDomain: 'fikr-apps.firebaseapp.com',
    storageBucket: 'fikr-apps.firebasestorage.app',
    measurementId: 'G-0Z1JVYRWVM',
  );

}